name: UE5 Build

on:
  pull_request:
    branches: [main]

jobs:
  Build:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          lfs: "true"
      
      - name: Build UE Project
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: 'C:/Unreal Engine/UE5.3_Source/Engine/Build/BatchFiles/RunUAT.bat'
          UPROJECT_PATH: ${{ github.workspace }}/UE5-Action-Combat-Course/ActionCombat.uproject
          BUILD_CONFIG: Development
          PLATFORM: Win64